- README.md
Starting my Open Source Carreer with an little contribution.
> Corrects code syntax for #time-parse section

- README.md
Changes are mostly syntax and consistency fixes, and a code example of the pitfalls of using class methods as scopes
> various changes as discussed in pull request #134, tidied in to one commit

- README.md
As discussed in https://github.com/bbatsov/rails-style-guide/issues/44#issuecomment-77745495
> Add more info about YAML config files.

- README.md
We start working on the German version and move it to separate repository.
> Added a link to the upcoming German translation.

- README.md
@katgironpe @bbatsov Thoughts?
> Fixes #151

- README.md
These methods return Relation objects that can be chained.
> Remove incorrect content about chaining scopes

- README.md
Added controller rendering tips found in "The Rails 4 Way" book.
> Controller rendering tips

- README.md
Also remove some extra spaces.
Thanks
> Remove extra space on named-scope-class

- README.md
Some notes about cluttering models with methods that should be helpers
> Add note about helper methods in models

- README.md
1) #inquiry method call in this example seems are unnecessary, but I may be wrong :)
2) Trim trailing white spaces from #158.
> Remove unnecessary method call at good example of Array#inquiry section.

- README.md
Sorry. Just can't resist to making this stupid pull-request...
The correct word is [persistence](http://dictionary.cambridge.org/dictionary/english/persistence)
> persistance -> persistence

- README.md
Rule to go along with Rails/SaveBang cop https://github.com/bbatsov/rubocop/pull/3280
> When persisting AR objects always use the exception raising bang! method or handle the method return value. 

- README.md
> [Add] Vietnamese version

- README.md
Link was not formatted as in other rules
@bbatsov
> Fix misplaced link

- README.md
Add a good/bad comparison and how-to.
@bbatsov
> Add good/bad comparison to Default migration values

- README.md
Related from https://github.com/bbatsov/rubocop/pull/3854
> Add rule of reversible migration

- README.md
HI,
We should do the [same](https://github.com/bbatsov/ruby-style-guide/pull/652) with the Rails Style Guide.
> Lowercase code blocks language identifier

- README.md
This translation will stay unfinished since I have no time for this project. Honestly removed :)
> Removed the unfinished German translation.

- README.md
Also see: https://github.com/bbatsov/rubocop/pull/5177
> Add rule about lexically scoped action filter

- README.md
Keep consistency with https://github.com/bbatsov/ruby-style-guide#prefer-raise-over-fail
> Prefer raise over fail

- README.md
Source: http://batsov.com/articles/2014/02/17/the-elements-of-style-in-ruby-number-13-length-vs-size-vs-count/#comment-1248998887
> Add size vs count/length rule

- README.md
Fix for this issue: 
**Naming convention Error #230**
> Fix name of model

- README.md
This matches the wording used in the `Rails/Validation` cop.
> Change language for validation styles

- README.md
Saying 'no more than two' seems very arbitrary.
> Update advice for shared instance variables

- README.md
I think models should generally not handle formatting issues, since this violates the Single Responsibility Principle by have business logic and presentation logic in the same class.
View helpers are fine for simple cases, but I find they are often overused.
> Update advice for complex view formatting

- README.md
Update links to HTTPS (where possible)
> Update links to HTTPS

- README.md
Since the linked page in the Guides already lists the full set of callbacks and their order, I don't think it's necessary to duplicate that in the style guide.
> Refine callbacks order example

- README.adoc
Related to https://github.com/rubocop-hq/rubocop-rails/pull/249, https://github.com/rubocop-hq/rubocop-rails/pull/278.
> Add entries for pluck and pick

- README.adoc
Fixes #240
See:
- https://12factor.net/dev-prod-parity
- https://12factor.net/config
> Discourage using dedicated staging environment

- README.adoc
https://boringrails.com/tips/rails-mailers-email-address-with-name
Hat tip to @swanson
> Use `email_address_with_name`

- README.adoc
If no argument is supplied, it only displays the help output.
> Fix Asciidoctor instructions

- README.adoc
> Add guidance for controller testing

- README.adoc
> Correct endless range example and provide some clarity

- README.adoc
Issue:https://github.com/rubocop/rubocop-rails/issues/565
> Add section for `where.not` with multiple attributes
