README.md
I can imagine that those extra `ppppp` characters were not typed deliberately.
:beers:
=> Fix a typppppo

README.md
Hello. [pureugong](https://github.com/pureugong) translated rails-style-guide into Korean.
=> Add korean translation link

README.md
I didn't see anything in this guide covering the format of multiline SQL strings used with methods like `find_by_sql` or `ActiveRecord::Base.connection.execute`. I know the preferred approach is to use ActiveRecord helpers, but as even the Rails guides themselves [admit](http://guides.rubyonrails.org/active_record_migrations.html#when-helpers-aren-t-enough), this isn't always sufficient. As such, I decided to include the practice we currently follow at OneLogin.
The content I added is pretty self-explanatory, but we use heredocs because they're [recommended](https://github.com/bbatsov/ruby-style-guide#percent-q-shorthand) for multiline strings and enable SQL syntax highlighting in many tools. Because the indentations and line breaks are only meant for readers of the source, the heredoc is …
=> Use Heredocs for multiline SQL

README.md
Add info about using shallow routes for nested routes more than 1 level deep.
This seems to be reasonable in order to avoid long urls for users (especially in case of long resource names like "payment_notification", "scheduled_appointment", etc.) and long url helpers for devs.
=> Add a note about shallow routes

README.md
The original description is confusing a bit. To clarify it, I added `locales/` prior to original submodule paths such as `models` and `views`.
=> Clarified internationalization submodules paths

README.md
Although this sample is under a "bad" code snippet, the thing to avoid is about something entirely different (i18n scoping), so I don't think we should use the older hash syntax anyway.
=> Use the new hash syntax

README.md
Depend as little as possible on `ActiveSupport`.
Added tips about usage of `ActiveSupport` extensions:
* `try!`,
* `starts_with`,
* `ends_with`,
* `in?`,
* `forty_two`,
* `inquiry`
=> Add ActiveSupport section

README.md
Hi guys,
When we have a has many association without the `dependent` option like Chat
has many messages and we destroy the Chat, the Message objects still have the
`chat_id` reference pointing to a Chat that was destroyed.
```
[1] pry(main)> chat = Chat.first
:id => 1,
:name => "Chat 01"
}
[2] pry(main)> message = chat.messages.first
:id => 1,
:message => "message 1",
:chat_id => 1,
}
[3] pry(main)> chat.destroy
[4] pry(main)> message.reload
:id => 1,
:message => "message 1",
:chat_id => 1,
}
[5] pry(main)> message.chat_id
1
[6] pry(main)> message.chat
nil
```
This patch add the `dependent` option to the has many and has one associations
to keep the things more explicit.
Thanks
=> Add the dependent option to the Active Record associations

README.md
Hello, Bozhidar!
Thanks for your gold mine of good advices.
Reading the style guides, I found advice that match twice ([one](https://github.com/bbatsov/rails-style-guide#find-each), [another one](https://github.com/bbatsov/rails-style-guide#find_each)) in the text (it seems to me):
So I found it necessary to remove the repetition.
Am I wrong? :)
Thanks.
=> Remove duplicated advice for find_each method using.

README.md
`find_by_attribute` is one the few bad things a ruby dev can do.  A benchmark is available here: http://lucianosousa.net/2016/01/17/rails-improvements-part-1-english-version.html explaining why it should be avoided.
=> Add a new bad option in find_by part

README.md
Enums are a meaningful addition to Rails model ecosystem and can be used in the majority of models where a field can take a limited selection of values, but bool is insufficient.
Placing their definition under attr macros is one way to go about it, another might be to put them above attr macros, right under constants.
I'd be glad to hear others' opinion on the matter.
=> Added enum macro recommendation

README.md
Rails has [symbols](http://billpatrianakos.me/blog/2013/10/13/list-of-rails-status-code-symbols/) for status codes. Why don't we use them by default? It would make more sense to the code.
=> Use symbols instead of numeric status codes

README.md
Figuring out FK constraints named `fk_rails_3232112` is not the coolest thing.
I suggest naming the FK constraints explicitly. 
@bbatsov
=> Add Migrations Foreign Key naming style

README.md
This book belongs in the "Further Reading" section as an equal of the other choices.
=> Add Rails 4 Test Prescriptions book reference

README.md
**change_column_default** method has self-descriptive name and it's usage is safer that change_column which is potentially danger (for example accidental column type change is possible).
One more advantage is that this method can be reversible in Rails 5 by specifying **from** & **to** parameter - [PR20018](https://github.com/rails/rails/pull/20018/files)
=> Change column default value by more appropriate method

README.md
Adds verdict after discussion in #143 
@bbatsov 
Note, addressed comments that would likely occur such as in https://github.com/bbatsov/rails-style-guide/pull/203/files/ea02a1394ba4710f645d6642a7c078466deb59ed
=> Add rule for models in migrations (#143)

README.md
Related rubocop pull request: bbatsov/rubocop#3825
Update information of `update_attribute` with all methods which skip model validations.
=> Add rule to avoid using model methods which skip validation

README.md
This has been upstreamed in Ruby 2.3: https://ruby-doc.org/core-2.3.0/Numeric.html#method-i-negative-3F
It also allows writing `(-2..2).select(&:positive?)` instead of `(-2..2).select { |i| i > 0 }` which is in line with https://github.com/bbatsov/ruby-style-guide#single-action-blocks
=> Remove Numeric#inquiry as bad

README.md
Recommends not doing things like:
```ruby
scope :chronological, -> { order(id: :asc) }
```
The sequence of ids is not guaranteed to be in any particular order, despite often (incidentally) being chronological. Use a timestamp column to order chronologically instead.
```ruby
scope :chronological, -> { order(created_at: :asc) }
```
=> Add recommendation to not order by `id`

README.md
avoid having multiple attributes listed in one `validates` expression which makes it harder to read
=> single attribute validations

README.md
This PR adds more specific description and examples to clarify the existing `find` and `find_by` rules.
Changes:
- Add an extra set of examples to favor `find_by` over `find_by_id` for the single-attribute case (`id: id`) in addition to the multiple-attribute case (`first_name: 'Bruce'` and `last_name: 'Wayne'`). Add comment clarifying the single-attribute dynamic finder is merely 'bad' style, while the multiple-attribute case is not only 'bad' but also 'deprecated in ActiveRecord 4.0, removed in 4.1+'. See #208 for related discussion.
- Clarify that `find` is favored only when you need to raise `ActiveRecord::RecordNotFound` when the record is not found, and compare it to the bang-methods `where.take!`, `find_by!`, and `find_by_id!` which exhibit similar behavior. See #183 and [#76 …
=> Clarify find and find_by rules

README.md
When giving good/bad examples about the guideline for using status code symbols instead of numeric values, give a good and a bad example with the same status code.
=> Match good and bad examples for status code guideline

README.md
As I reported in #233, `String#to_time` has the same behaviour as `Time.parse` and hence probably should also be considered bad style.
=> Add section about String#to_time

README.md
It is a bad practice to use instance variables in partials for several reasons. Some more of them can be found here http://rails-bestpractices.com/posts/2010/07/24/replace-instance-variable-with-local-variable/
=> Never use instance variables in partials

README.md
"find_by(id: id)" was used as good practice
=> Use "find(id)" instead of "find_by(id: id)"

README.md
I think this advice doesn't belong in the style guide.
Using `_path` instead of `_url` is simply a bug, it's not a matter of style or preference.
=> Remove section about mailer paths

README.md
As mentioned by @pirj in #246, since apidock is no longer updated.
=> Replace apidock.com links with official docs

README.adoc
Align the guide to mention corresponding RuboCop extension like the Ruby Style Guide mentions RuboCop itself.
=> Mention rubocop-rails

README.adoc
Section titles were mostly auto-generated during AsciiDoc conversion, and some of them were off.
But the main culprit that they were not using proper Title Case.
=> Use proper Title Case in section titles

README.adoc
This PR uses proper names of Rails compornents.
> The proper names of Rails components have a space in between the words,
> like “Active Support”. `ActiveRecord` is a Ruby module, whereas Active Record is an ORM.
https://github.com/rails/rails/blob/v6.0.0.rc1/guides/source/api_documentation_guidelines.md#wording
=> Use proper names of Rails compornents

README.adoc
Dynamic finder methods (`DynamicMatchers`)  has not been previously deprecated.
AFAIK, next release Rails 6.0 has also no plans to deprecate it.
https://github.com/rails/rails/blob/v6.0.0.rc1/activerecord/lib/active_record/dynamic_matchers.rb
So, it seems that this was written incorrectly when I refer to the following.
- https://github.com/rubocop-hq/rails-style-guide/pull/220
- https://github.com/rubocop-hq/rails-style-guide/issues/208
Therefore this PR removes the incorrect example comment for `find_by`.
=> Remove an incorrect comment for `find_by` example

README.adoc
Closes https://github.com/rubocop-hq/rails-style-guide/issues/144
Ref: https://github.com/rubocop-hq/rubocop-rails/issues/78
=> Add section for hash syntax of enums

README.adoc
I think gender isn't a good example for a specifically limited set of valid options. Changing it to a user role example both communicates the intended message and isn't exclusionary.
=> Changed example enum

README.adoc
A minor typo that I accidentally encounter when referencing this style guide
=> Fix typo at Controller Rendering chapter

README.adoc
related to rubocop-hq/rubocop-rails#340
When you read:
```ruby
in_5_hours = 5.hours.from_now
```
it is easy to understand that it is a time that will happen in 5 hours from this moment.
In the other hand, 
```ruby
in_5_hours = 5.hours.since 
```
when you read it, you ask yourself, "since what?" I had to go to the method definition and find out that `since` receives a parameter that defaults to `::Time.current`, thats not evident at first sight.
we should encourage the usage of `.from_now` instead of `.since` without parameter
Using a `since` with a parameter is totally fine though
```ruby
yesterday = 1.day.ago
tomorrow = 2.days.since(yesterday)
```
=> In durations, make sure method usage reads as plain english

README.adoc
Passing conditions as a hash is always preferable to using an SQL fragment, regardless of whether the conditions are negated.
=> Extend query conditions guideline to cover equality

README.adoc
For models which don't need to be backed by a database, the built-in ActiveModel modules work perfectly fine, so we don't need to recommend a 3rd party gem.
E.g. validations are already mixed into `ActiveModel::Model`, and starting with modern versions of rails the attributes API is supported through `ActiveModel::Attributes`. For earlier versions, a simple `#attr_accessor` declaration does the trick.
=> Recommend ActiveModel native modules over ActiveAttr gem

README.adoc
Issue: https://github.com/rubocop-hq/rubocop-rails/issues/337
Ref: https://thoughtbot.com/blog/avoid-the-threestate-boolean-problem
=> Add three-state boolean problem

README.adoc
Not loading the defaults will set you back on important Rails framework defaults, e.g.:
- action_view.default_enforce_utf8
- action_controller.default_protect_from_forgery
- active_record.belongs_to_required_by_default
and is sometimes hard to notice.
https://guides.rubyonrails.org/configuring.html#results-of-config-load-defaults
Fixes #277
=> Add a guideline to load config defaults

README.adoc
Fixes #223
Better viewed as https://github.com/rubocop-hq/rails-style-guide/blob/custom-validation-method-naming/README.adoc#custom-validation-methods
=> Add Custom Validation Methods naming guideline

README.adoc
Hi!
According to the [docs](https://apidock.com/rails/ActionMailer/Base/email_address_with_name/class) we have to pass the email by first parameter to the method and the name as a second one.
Otherwise we will catch an `Mail::Field::IncompleteParseError`.
Best regards,
Georgiy
=> Change params order for email_address_with_name method

README.adoc
This little change fixes the code highlighting in two places, which only seems to happen on the generated doc (when using asciidoctor + rouge):
=> Fix code highlighting issues

README.adoc
There are 10 uses of `prefer...over` but only 4 uses of `favor...over`.
(Using `prefer` also avoids having to deal with the different spellings `favor`).
=> Use consistent language for `prefer` vs `favor`

README.adoc
The introduction uses "I", but as the guide is no longer under Bozhidar's account, it's not clear who this refers to.
=> Add original author credit

README.adoc
I think we need to have some kind of cut-off for translations that are no longer updated. I'm proposing we remove the ones that haven't been updated for over 5 years.
=> Remove stale translations

README.adoc
This changed in Rails 5:
https://www.bigbinary.com/blog/application-record-in-rails-5
=> Replace references to `ActiveRecord::Base` with `ApplicationRecord`

README.adoc
I expect this was added before Bundler had proper support for multiple platforms.
=> Remove outdated platform advice

README.adoc
Follow up https://github.com/rails/rails/pull/44354.
Also, the deprecated warning for `to_s(:db)` is `to_fs(:db)` instead of `to_formatted_s(:db)`.
> DateTime#to_s(:db) is deprecated. Please use DateTime#to_fs(:db) instead.
=> Add "Prefer `to_fs`" rule

.github/workflows/spell_checking.yml
Reference: https://github.blog/changelog/2022-04-25-git-io-deprecation/
=> Update links that make use of deprecated git.io

README.adoc
Setting may overwrite previous assignments and that is almost always a mistake.
See also https://github.com/rubocop/rubocop-rails/pull/514
=> Prefer appending to setting `ignored_columns`

README.adoc
Along the way, clarify [Lazy lookup](https://guides.rubyonrails.org/i18n.html#lazy-lookup) guideline a bit:
"the texts" is quite vague, as it stands for:
> strings and other locale specific bits (such as date or currency formats)
I believe "entries" is a better term.
Lazy lookup is also available in controllers, see https://github.com/rails/rails/blob/fee61e3abc878e4d4930a0be0accf8e4569009a8/actionpack/lib/abstract_controller/translation.rb#L11
PS Except `ActionController::Api`. Only `ActionController::Base`.
=> Relax dot-separated locale keys guideline

README.adoc
Follow up https://github.com/rubocop/rubocop-rails/pull/706.
This PR adds "Prefer using squiggly heredoc over `strip_heredoc`" rule.
=> Add "Prefer using squiggly heredoc over `strip_heredoc`" rule

README.adoc
Since there are several ways to indicate the current time, we believe that `freeze_time`, which can be expressed as simply as possible, should be preferred.
```ruby
travel_to(Time.now)
travel_to(DateTime.now)
travel_to(Time.current)
travel_to(Time.zone.now)
travel_to(Time.now.in_time_zone)
travel_to(Time.current.to_time)
freeze_time
```
=> Add "Prefer `freeze_time` over `travel_to` with an argument of the current time" rule

README.adoc
If you're using Rails 6.1 or higher, prefer `where.missing` over `left_joins` and `where` to find missing relationship records.
It can be expressed in a more simplified.
```ruby
Post.left_joins(:author).where(authors: { id: nil })
Post.where.missing(:author)
```
=> Add "Finding missing relationship records" rule

README.adoc
Follow up https://github.com/rubocop/rubocop-rails/pull/730.
This PR adds new "Prefer `all_(day|week|month|quarter|year)` over range of date/time" rule.
```ruby
date.beginning_of_day..date.end_of_day
date.beginning_of_week..date.end_of_week
date.beginning_of_month..date.end_of_month
date.beginning_of_quarter..date.end_of_quarter
date.beginning_of_year..date.end_of_year
date.all_day
date.all_week
date.all_month
date.all_quarter
date.all_year
```
=> Add new "Prefer `all_(day|week|month|quarter|year)` over range of date/time" rule

README.adoc
Related issue: https://github.com/rubocop/rails-style-guide/issues/339
This PR adds "Redundant `all`" section.
=> Add section for redundant `all`

codespell.txt
When I opened https://github.com/rubocop/rails-style-guide/pull/348, the CI's spellcheck failed. 
https://github.com/rubocop/rails-style-guide/actions/runs/6570237096/job/17847343002?pr=348
I addressed the issue by adding the relevant word to the whitelist.
=> Add word that failed in CI's spell check to the whitelist

README.adoc
As pointed out https://github.com/rubocop/rails-style-guide/issues/347, when the receiver of `all` is an association, there are methods whose behavior changes when `all` is omitted.
So, I've added a note to caution against omitting these methods.
=> Add note to redundant-all section about `all` receiver being an association

README.adoc
It appears PragProg updated "book" to "titles" in their URL structure. Additionally, I added the second edition of the Cucumber book as the destination for "The Cucumber Book".
=> Un-break PragProg links

README.adoc
Adds a section for [`order`](https://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-order) arguments, giving preference to symbol arguments over strings.
PR for the cop: https://github.com/rubocop/rubocop-rails/pull/1501
=> Add Order arguments section
